import type { AffiliateProduct } from '@/lib/affiliate'

export interface AdvisorPost {
  slug: string
  title: string
  description: string
  products: AffiliateProduct[]
  personas: string[]
  topics: string[]
}

// Each entry is backed by src/content/blog/{slug}/metadata.json. Keep this
// list deliberately small so the advisor has useful choices without guessing.
export const ADVISOR_CATALOG = [
  {
    slug: 'granola-ai-review',
    title: 'Granola AI Review: The App I Use Every Meeting',
    description: 'Zack’s account of using Granola for daily meeting notes, including its local audio capture and bot-free approach.',
    products: ['granola'],
    personas: ['founders', 'consultants', 'knowledge workers'],
    topics: ['review', 'meeting notes', 'privacy'],
  },
  {
    slug: 'how-to-transcribe-meetings-without-bot',
    title: 'How to Transcribe Meetings Without a Bot Joining Your Call',
    description: 'The top-converting guide to private meeting notes through on-device audio capture, with no bot in the call.',
    products: ['granola'],
    personas: ['everyone', 'consultants', 'client services', 'sensitive calls'],
    topics: ['meeting notes', 'no bot', 'client calls', 'privacy'],
  },
  {
    slug: 'how-to-transcribe-zoom-meetings-without-bot',
    title: 'How to Transcribe Zoom Meetings Without a Bot',
    description: 'A Zoom-specific guide to transcripts, summaries, and action items without adding a notetaker participant.',
    products: ['granola'],
    personas: ['Zoom users', 'consultants', 'sales', 'client services'],
    topics: ['Zoom', 'meeting notes', 'no bot', 'client calls'],
  },
  {
    slug: 'best-ai-meeting-notes-2026',
    title: 'Best AI Meeting Notes in 2026: Why I Switched to Granola',
    description: 'A comparison of AI meeting note options centered on bot-free capture and useful notes after the call.',
    products: ['granola'],
    personas: ['buyers', 'knowledge workers', 'consultants'],
    topics: ['best tools', 'meeting notes', 'comparison', 'no bot'],
  },
  {
    slug: 'how-to-record-meetings-2026',
    title: 'How to Record Meetings in 2026: Best AI Tools Without a Bot',
    description: 'A practical guide to recording and transcribing Zoom, Google Meet, and Teams calls without a meeting bot.',
    products: ['granola'],
    personas: ['knowledge workers', 'consultants', 'remote teams'],
    topics: ['recording', 'transcription', 'meeting notes', 'no bot'],
  },
  {
    slug: 'granola-free-plan-what-you-get',
    title: "Granola's Three Free Months: What's Actually Included",
    description: 'A practical look at the three-month offer and how to judge the paid plan for your workflow.',
    products: ['granola'],
    personas: ['new users', 'buyers'],
    topics: ['pricing', 'free offer', 'plans'],
  },
  {
    slug: 'granola-vs-otter',
    title: 'Granola vs Otter.ai: I Tested Both for Months',
    description: 'A hands-on comparison of bot-free meeting notes and live, shared transcription.',
    products: ['granola'],
    personas: ['teams', 'consultants'],
    topics: ['comparison', 'live captions', 'meeting bots'],
  },
  {
    slug: 'granola-vs-fireflies',
    title: 'Granola vs Fireflies.ai: Privacy vs Team Meeting AI Comparison',
    description: 'A comparison focused on private, unobtrusive notes versus team features and sales workflows.',
    products: ['granola'],
    personas: ['sales teams', 'client services'],
    topics: ['comparison', 'privacy', 'CRM'],
  },
  {
    slug: 'granola-vs-fathom',
    title: 'Granola vs Fathom: Invisible vs Visible Meeting AI Recording',
    description: 'How Granola’s bot-free capture compares with Fathom’s visible meeting assistant.',
    products: ['granola'],
    personas: ['Zoom teams', 'small teams'],
    topics: ['comparison', 'free tools', 'meeting bots'],
  },
  {
    slug: 'granola-for-sales-teams-2026',
    title: 'Granola for Sales Teams in 2026: AI Meeting Notes That Close More Deals',
    description: 'Ways sales teams can capture prospect details, prepare deal reviews, and write follow-ups.',
    products: ['granola'],
    personas: ['sales', 'account executives'],
    topics: ['sales calls', 'follow-up', 'deal reviews'],
  },
  {
    slug: 'granola-for-consultants',
    title: 'Granola for Consultants: AI Meeting Assistant for Consulting Professionals 2026',
    description: 'A guide to client meeting notes, project documentation, and consulting follow-ups.',
    products: ['granola'],
    personas: ['consultants', 'agencies'],
    topics: ['client meetings', 'project notes', 'consulting'],
  },
  {
    slug: 'granola-for-therapists-2026',
    title: 'Granola for Therapists in 2026: AI Session Notes That Keep You Present With Clients',
    description: 'How therapists can document sessions while staying focused on the person in front of them.',
    products: ['granola'],
    personas: ['therapists', 'counselors', 'coaches'],
    topics: ['sensitive meetings', 'session notes', 'presence'],
  },
  {
    slug: 'granola-for-engineers',
    title: 'Granola for Engineers: AI Meeting Notes for Technical Teams',
    description: 'Meeting notes for design reviews, incident retrospectives, planning, and technical decisions.',
    products: ['granola'],
    personas: ['engineers', 'technical teams'],
    topics: ['design reviews', 'retrospectives', 'planning'],
  },
  {
    slug: 'granola-for-recruiters',
    title: 'Granola for Recruiters: AI Meeting Assistant for Recruiting Professionals 2026',
    description: 'A guide to candidate interviews, client intake, and hiring pipeline documentation.',
    products: ['granola'],
    personas: ['recruiters', 'talent teams'],
    topics: ['interviews', 'candidate notes', 'hiring'],
  },
  {
    slug: 'granola-for-researchers-2026',
    title: 'Granola for Researchers in 2026: AI Meeting Notes for Interviews, Focus Groups, and Academic Meetings',
    description: 'Capturing interviews, focus groups, and research meetings while staying present.',
    products: ['granola'],
    personas: ['researchers', 'academics', 'user researchers'],
    topics: ['research interviews', 'focus groups', 'qualitative research'],
  },
  {
    slug: 'granola-for-startup-founders',
    title: 'Granola for Startup Founders: AI Meeting Notes for Investor Calls and Team Syncs',
    description: 'Notes for investor calls, board meetings, customer conversations, and team syncs.',
    products: ['granola'],
    personas: ['founders', 'executives'],
    topics: ['investor calls', 'board meetings', 'team syncs'],
  },
  {
    slug: 'wisprflow-review',
    title: 'WisprFlow Review: I Write Code at 179 WPM',
    description: 'Zack’s review of dictating code, documentation, messages, and long-form writing with WisprFlow.',
    products: ['wisprflow'],
    personas: ['engineers', 'writers'],
    topics: ['review', 'voice typing', 'coding'],
  },
  {
    slug: 'wisprflow-pricing-guide-2026',
    title: 'WisprFlow Pricing Guide 2026: Is It Worth the Investment?',
    description: 'A breakdown of WisprFlow plans, costs, and the workflows that can justify paying for it.',
    products: ['wisprflow'],
    personas: ['buyers', 'teams'],
    topics: ['pricing', 'plans', 'value'],
  },
  {
    slug: 'wisprflow-vs-superwhisper',
    title: 'WisprFlow vs Superwhisper: Which Voice Typing Tool Wins?',
    description: 'Cloud-based voice typing compared with local Whisper models for Mac workflows.',
    products: ['wisprflow'],
    personas: ['Mac users', 'privacy-conscious users'],
    topics: ['comparison', 'local models', 'voice typing'],
  },
  {
    slug: 'wisprflow-vs-apple-dictation-2026',
    title: 'WisprFlow vs Apple Dictation 2026: Which iPhone Voice Tool Wins?',
    description: 'A comparison of accuracy, editing features, and daily use on Apple devices.',
    products: ['wisprflow'],
    personas: ['iPhone users', 'Mac users'],
    topics: ['comparison', 'Apple Dictation', 'mobile'],
  },
  {
    slug: 'wisprflow-claude-code-setup-guide',
    title: 'How to Set Up WisprFlow and Claude Code',
    description: 'A step-by-step setup for controlling Claude Code with voice input.',
    products: ['wisprflow'],
    personas: ['engineers', 'Claude Code users'],
    topics: ['setup', 'voice coding', 'Claude Code'],
  },
  {
    slug: 'wisprflow-for-engineers',
    title: 'WisprFlow for Software Engineers: Voice-Driven Coding and Documentation',
    description: 'Voice workflows for code comments, technical docs, pull requests, and team messages.',
    products: ['wisprflow'],
    personas: ['engineers', 'developers'],
    topics: ['coding', 'documentation', 'pull requests'],
  },
  {
    slug: 'wisprflow-for-writers',
    title: 'WisprFlow for Writers: Voice Transcription That Understands Creative Flow',
    description: 'Voice workflows for capturing ideas, drafting articles, and writing longer pieces.',
    products: ['wisprflow'],
    personas: ['writers', 'bloggers', 'content creators'],
    topics: ['long-form writing', 'drafting', 'ideas'],
  },
  {
    slug: 'wisprflow-for-sales-teams',
    title: 'WisprFlow for Sales: Voice Transcription That Accelerates Deal Velocity',
    description: 'Dictation workflows for follow-up emails, CRM notes, and opportunity updates.',
    products: ['wisprflow'],
    personas: ['sales', 'account executives'],
    topics: ['follow-up', 'CRM notes', 'email'],
  },
  {
    slug: 'wisprflow-for-consultants',
    title: 'Why Management Consultants Choose Voice-First Development',
    description: 'Using voice input to draft client work and create prototypes quickly.',
    products: ['wisprflow'],
    personas: ['consultants', 'strategists'],
    topics: ['prototyping', 'client work', 'dictation'],
  },
  {
    slug: 'wisprflow-for-therapists',
    title: 'WisprFlow for Therapists: Voice-to-Text Session Notes That Protect Privacy',
    description: 'Voice-to-text workflows for session documentation and progress notes.',
    products: ['wisprflow'],
    personas: ['therapists', 'counselors'],
    topics: ['session notes', 'documentation', 'voice typing'],
  },
  {
    slug: 'firecrawl-api-guide-2026',
    title: 'Firecrawl API Reference and Usage Guide (2026)',
    description: 'A practical guide to authentication, endpoints, rate limits, pricing, and integration.',
    products: ['firecrawl'],
    personas: ['developers', 'AI engineers'],
    topics: ['API', 'web scraping', 'integration'],
  },
  {
    slug: 'firecrawl-for-rag-pipelines',
    title: 'Using Firecrawl for RAG Pipelines',
    description: 'Scraping and preparing web content for RAG, from single pages to full-site crawls.',
    products: ['firecrawl'],
    personas: ['AI engineers', 'developers'],
    topics: ['RAG', 'crawling', 'markdown', 'data extraction'],
  },
  {
    slug: 'firecrawl-vs-apify',
    title: 'Firecrawl vs Apify: Which Web Scraping Platform is Better for AI Workflows?',
    description: 'A comparison of content output, pricing, integrations, and fit for AI applications.',
    products: ['firecrawl'],
    personas: ['developers', 'data teams'],
    topics: ['comparison', 'Apify', 'web scraping'],
  },
  {
    slug: 'firecrawl-vs-crawl4ai',
    title: 'Firecrawl vs Crawl4AI: Which Web Crawler is Better for AI?',
    description: 'Managed API and open-source crawling compared by features, costs, and maintenance.',
    products: ['firecrawl'],
    personas: ['developers', 'platform teams'],
    topics: ['comparison', 'Crawl4AI', 'open source'],
  },
  {
    slug: 'firecrawl-for-recruiters',
    title: 'How Recruiters Use Web Scraping to Source Candidates and Track Job Markets',
    description: 'Web data collection for candidate sourcing, market analysis, and recruiting research.',
    products: ['firecrawl'],
    personas: ['recruiters', 'talent teams'],
    topics: ['candidate sourcing', 'job markets', 'web scraping'],
  },
  {
    slug: 'firecrawl-for-academia',
    title: 'Web Scraping for Academic Research: Literature Review, Citation Analysis, and Data Collection',
    description: 'Web collection methods for literature reviews, citation work, and academic datasets.',
    products: ['firecrawl'],
    personas: ['researchers', 'academics'],
    topics: ['literature review', 'citations', 'research data'],
  },
  {
    slug: 'firecrawl-for-ecommerce',
    title: 'Web Scraping for E-Commerce: Price Monitoring and Market Intelligence',
    description: 'Web data workflows for price monitoring, inventory tracking, and market research.',
    products: ['firecrawl'],
    personas: ['e-commerce teams', 'analysts'],
    topics: ['pricing', 'inventory', 'market research'],
  },
  {
    slug: 'firecrawl-for-seo',
    title: 'Web Scraping for SEO: Competitor Analysis, Keyword Tracking, and Content Gaps',
    description: 'Using web data for competitor research, keyword gaps, and technical SEO monitoring.',
    products: ['firecrawl'],
    personas: ['SEO teams', 'marketers'],
    topics: ['SEO', 'competitor research', 'content gaps'],
  },
] as const satisfies readonly AdvisorPost[]

export type AdvisorPostSlug = (typeof ADVISOR_CATALOG)[number]['slug']

export const ADVISOR_POSTS_BY_SLUG = Object.fromEntries(
  ADVISOR_CATALOG.map((post) => [post.slug, post]),
) as Record<AdvisorPostSlug, (typeof ADVISOR_CATALOG)[number]>
