import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

// Tooling data extracted from git diff
const toolsData = [
  {
    id: "openai",
    name: "OpenAI API",
    description:
      "Provides access to OpenAI's powerful language models like GPT-4o, GPT-4, and GPT-3.5 Turbo for various natural language processing tasks.",
    category: "llm",
    categoryName: "LLM APIs",
    pricing: "Pay-per-token",
    websiteUrl: "https://openai.com/api/",
    githubUrl: undefined,
    logoUrl: "/placeholder.svg?height=40&width=40",
    features: [
      "Access to state-of-the-art LLMs",
      "Fine-tuning capabilities",
      "Embeddings API",
      "Image generation (DALL-E)",
      "Speech-to-text (Whisper)",
    ],
    pros: [
      "High model performance",
      "Extensive documentation and community support",
      "Easy integration",
      "Regular updates and new features",
      "Wide range of applications",
    ],
    cons: [
      "Can be expensive for high usage",
      "Rate limits on free/lower tiers",
      "Potential for biased or harmful outputs",
      "API changes can require code updates",
    ],
    openSource: false,
    apiAccess: true,
    documentationQuality: "Excellent",
    communitySize: "Very Large",
    lastUpdated: "May 2024",
    languages: ["Python", "Node.js", "Ruby", "Java", "Go"],
    reviewCount: 1243,
    reviewUrl: "https://example.com/reviews/openai",
  },
  {
    id: "langchain",
    name: "LangChain",
    description:
      "LangChain is a framework for developing applications powered by language models. It provides tools for chaining together multiple components to create more complex applications.",
    category: "framework",
    categoryName: "AI Frameworks",
    pricing: "Free (Open Source)",
    websiteUrl: "https://langchain.com/",
    githubUrl: "https://github.com/langchain-ai/langchain",
    logoUrl: "/placeholder.svg?height=40&width=40",
    features: [
      "Chains for combining multiple LLM calls",
      "Agents for dynamic tool selection",
      "Memory for maintaining conversation state",
      "Document loaders and text splitters",
      "Vector stores integration",
    ],
    pros: [
      "Highly flexible and composable",
      "Active community and development",
      "Supports multiple LLM providers",
      "Extensive documentation and examples",
      "Simplifies complex LLM workflows",
    ],
    cons: [
      "Steep learning curve for beginners",
      "Can be complex for simple use cases",
      "Documentation can be fragmented across versions",
      "Performance overhead for some components",
    ],
    openSource: true,
    apiAccess: true,
    documentationQuality: "Good",
    communitySize: "Large",
    lastUpdated: "June 2024",
    languages: ["Python", "TypeScript/JavaScript"],
    reviewCount: 876,
    reviewUrl: "https://example.com/reviews/langchain",
  },
  {
    id: "pinecone",
    name: "Pinecone",
    description:
      "Pinecone is a vector database designed for machine learning applications. It enables efficient similarity search for embeddings, making it ideal for semantic search, recommendations, and more.",
    category: "vector-db",
    categoryName: "Vector Databases",
    pricing: "Freemium",
    websiteUrl: "https://www.pinecone.io/",
    githubUrl: undefined,
    logoUrl: "/placeholder.svg?height=40&width=40",
    features: [
      "Vector similarity search",
      "Real-time updates",
      "Horizontal scaling",
      "Metadata filtering",
      "Hybrid search capabilities",
    ],
    pros: [
      "Fast query performance",
      "Easy to integrate with LLM applications",
      "Managed service with high availability",
      "Good documentation and examples",
      "Serverless option available",
    ],
    cons: [
      "Free tier limitations",
      "Higher cost at scale compared to self-hosted alternatives",
      "Limited customization options",
      "Learning curve for optimal index configuration",
    ],
    openSource: false,
    apiAccess: true,
    documentationQuality: "Very Good",
    communitySize: "Medium",
    lastUpdated: "April 2024",
    languages: ["Python", "Node.js", "Java"],
    reviewCount: 542,
    reviewUrl: "https://example.com/reviews/pinecone",
  },
  {
    id: "llamaindex",
    name: "LlamaIndex",
    description:
      "LlamaIndex (formerly GPT Index) is a data framework for LLM applications to ingest, structure, and access private or domain-specific data for context-augmented generation.",
    category: "framework",
    categoryName: "AI Frameworks",
    pricing: "Free (Open Source)",
    websiteUrl: "https://www.llamaindex.ai/",
    githubUrl: "https://github.com/jerryjliu/llama_index",
    logoUrl: "/placeholder.svg?height=40&width=40",
    features: [
      "Data connectors for various sources",
      "Indexing strategies for efficient retrieval",
      "Query engines for different use cases",
      "Evaluation tools for RAG systems",
      "Agent frameworks for complex workflows",
    ],
    pros: [
      "Specialized for RAG applications",
      "Flexible data ingestion options",
      "Good documentation with examples",
      "Active development and community",
      "Works well with various LLM providers",
    ],
    cons: [
      "Can be complex for beginners",
      "Documentation sometimes lags behind features",
      "Performance can vary based on configuration",
      "Less mature than some alternatives",
    ],
    openSource: true,
    apiAccess: true,
    documentationQuality: "Good",
    communitySize: "Medium",
    lastUpdated: "May 2024",
    languages: ["Python", "TypeScript/JavaScript"],
    reviewCount: 328,
    reviewUrl: "https://example.com/reviews/llamaindex",
  },
  {
    id: "anthropic",
    name: "Anthropic Claude API",
    description:
      "Anthropic's Claude is a family of AI assistants known for their helpfulness, harmlessness, and honesty. The API provides access to Claude models for various text generation tasks.",
    category: "llm",
    categoryName: "LLM APIs",
    pricing: "Pay-per-token",
    websiteUrl: "https://www.anthropic.com/claude",
    githubUrl: undefined,
    logoUrl: "/placeholder.svg?height=40&width=40",
    features: [
      "Access to Claude 3 model family (Opus, Sonnet, Haiku)",
      "Long context windows (up to 200K tokens)",
      "Tool use capabilities",
      "Vision capabilities",
      "Constitutional AI approach for safety",
    ],
    pros: [
      "Strong reasoning capabilities",
      "Excellent instruction following",
      "Less prone to hallucinations",
      "Good at nuanced responses",
      "Competitive pricing",
    ],
    cons: [
      "Fewer integration options than some competitors",
      "Less community resources available",
      "More limited ecosystem of tools",
      "Newer to market than some alternatives",
    ],
    openSource: false,
    apiAccess: true,
    documentationQuality: "Very Good",
    communitySize: "Medium",
    lastUpdated: "June 2024",
    languages: ["Python", "Node.js", "Ruby"],
    reviewCount: 687,
    reviewUrl: "https://example.com/reviews/anthropic",
  },
  {
    id: "chroma",
    name: "Chroma",
    description:
      "Chroma is an open-source embedding database designed for building AI applications with embeddings and vector search capabilities.",
    category: "vector-db",
    categoryName: "Vector Databases",
    pricing: "Free (Open Source)",
    websiteUrl: "https://www.trychroma.com/",
    githubUrl: "https://github.com/chroma-core/chroma",
    logoUrl: "/placeholder.svg?height=40&width=40",
    features: [
      "In-memory and persistent storage options",
      "Metadata filtering",
      "Multiple distance functions",
      "Easy integration with LLM frameworks",
      "Collection management",
    ],
    pros: [
      "Simple API and easy to get started",
      "Fully open source",
      "Good integration with LangChain and other frameworks",
      "Active development",
      "Low resource requirements for small projects",
    ],
    cons: [
      "Less scalable than some commercial alternatives",
      "Fewer advanced features",
      "Limited performance optimizations",
      "Documentation could be more comprehensive",
    ],
    openSource: true,
    apiAccess: true,
    documentationQuality: "Good",
    communitySize: "Medium",
    lastUpdated: "May 2024",
    languages: ["Python", "TypeScript/JavaScript"],
    reviewCount: 215,
    reviewUrl: "https://example.com/reviews/chroma",
  },
  {
    id: "autogen",
    name: "AutoGen",
    description:
      "AutoGen is a framework for building LLM applications using multiple agents that can converse with each other to solve tasks. It enables complex workflows through agent collaboration.",
    category: "agent",
    categoryName: "Agent Frameworks",
    pricing: "Free (Open Source)",
    websiteUrl: "https://microsoft.github.io/autogen/",
    githubUrl: "https://github.com/microsoft/autogen",
    logoUrl: "/placeholder.svg?height=40&width=40",
    features: [
      "Multi-agent conversations",
      "Customizable agent behaviors",
      "Human-in-the-loop capabilities",
      "Tool use and function calling",
      "Group chat for multiple agents",
    ],
    pros: [
      "Powerful multi-agent architecture",
      "Backed by Microsoft research",
      "Flexible and extensible",
      "Good for complex reasoning tasks",
      "Active development",
    ],
    cons: [
      "Steep learning curve",
      "Documentation could be more comprehensive",
      "Requires careful prompt engineering",
      "Can be resource intensive",
    ],
    openSource: true,
    apiAccess: true,
    documentationQuality: "Moderate",
    communitySize: "Growing",
    lastUpdated: "April 2024",
    languages: ["Python"],
    reviewCount: 156,
    reviewUrl: "https://example.com/reviews/autogen",
  },
  {
    id: "mistral",
    name: "Mistral AI",
    description:
      "Mistral AI offers a range of open and closed source language models known for their efficiency and performance. Their API provides access to models like Mistral Large and Mixtral.",
    category: "llm",
    categoryName: "LLM APIs",
    pricing: "Pay-per-token",
    websiteUrl: "https://mistral.ai/",
    githubUrl: "https://github.com/mistralai",
    logoUrl: "/placeholder.svg?height=40&width=40",
    features: [
      "Access to Mistral Large and Mixtral models",
      "Open-weights models available",
      "Function calling capabilities",
      "Embeddings API",
      "Competitive performance",
    ],
    pros: [
      "Strong performance-to-cost ratio",
      "Open-weights options available",
      "European-based alternative to US providers",
      "Regular model improvements",
      "Simple API",
    ],
    cons: [
      "Newer to market with less ecosystem",
      "Fewer features than some competitors",
      "Documentation could be more comprehensive",
      "Limited tooling compared to larger providers",
    ],
    openSource: true,
    apiAccess: true,
    documentationQuality: "Good",
    communitySize: "Growing",
    lastUpdated: "May 2024",
    languages: ["Python", "Node.js"],
    reviewCount: 312,
    reviewUrl: "https://example.com/reviews/mistral",
  },
  {
    id: "ragas",
    name: "RAGAS",
    description:
      "RAGAS is an open-source framework for evaluating Retrieval Augmented Generation (RAG) systems, providing metrics and tools to assess the quality of RAG pipelines.",
    category: "evaluation",
    categoryName: "Evaluation Tools",
    pricing: "Free (Open Source)",
    websiteUrl: "https://docs.ragas.io/",
    githubUrl: "https://github.com/explodinggradients/ragas",
    logoUrl: "/placeholder.svg?height=40&width=40",
    features: [
      "Comprehensive RAG evaluation metrics",
      "Faithfulness assessment",
      "Context relevance scoring",
      "Answer relevance evaluation",
      "Integration with LangChain and LlamaIndex",
    ],
    pros: [
      "Specialized for RAG evaluation",
      "Multiple evaluation dimensions",
      "Easy integration with popular frameworks",
      "Active development",
      "Good documentation",
    ],
    cons: [
      "Requires LLM access for some metrics",
      "Can be resource intensive",
      "Limited to RAG use cases",
      "Some metrics can be subjective",
    ],
    openSource: true,
    apiAccess: true,
    documentationQuality: "Good",
    communitySize: "Small but growing",
    lastUpdated: "April 2024",
    languages: ["Python"],
    reviewCount: 87,
    reviewUrl: "https://example.com/reviews/ragas",
  },
  {
    id: "ollama",
    name: "Ollama",
    description:
      "Ollama is a tool for running open-source large language models locally. It simplifies the process of downloading, setting up, and running models like Llama, Mistral, and others on your own hardware.",
    category: "llm",
    categoryName: "LLM APIs",
    pricing: "Free (Open Source)",
    websiteUrl: "https://ollama.ai/",
    githubUrl: "https://github.com/ollama/ollama",
    logoUrl: "/placeholder.svg?height=40&width=40",
    features: [
      "Run models locally on your hardware",
      "Simple CLI and API",
      "Support for many open-source models",
      "Model customization with Modelfiles",
      "GPU acceleration",
    ],
    pros: [
      "Complete privacy - data stays local",
      "No usage costs or API keys",
      "Easy to set up and use",
      "Active community",
      "Works offline",
    ],
    cons: [
      "Performance depends on local hardware",
      "Limited to available open-source models",
      "Higher resource requirements",
      "Less powerful than cloud-based alternatives",
      "Limited to text generation (no embeddings)",
    ],
    openSource: true,
    apiAccess: true,
    documentationQuality: "Good",
    communitySize: "Large",
    lastUpdated: "June 2024",
    languages: ["Go", "Python", "JavaScript"],
    reviewCount: 423,
    reviewUrl: "https://example.com/reviews/ollama",
  },
  // ==================== 15 NEW TOOLS ====================
  {
    id: "github-copilot",
    name: "GitHub Copilot",
    description:
      "An AI-powered code completion tool developed by GitHub and OpenAI, offering real-time suggestions and code generation within popular IDEs.",
    category: "coding-assistant",
    categoryName: "Coding Assistants",
    pricing: "Subscription",
    websiteUrl: "https://github.com/features/copilot",
    githubUrl: undefined,
    logoUrl: "/placeholder.svg?height=40&width=40",
    features: [
      "Supports multiple models, including GPT-4o, Claude 3.5, and Gemini 1.5 Pro",
      "Provides multi-file editing capabilities",
      "Integrates with Visual Studio Code, JetBrains, and Neovim",
      "Introduced 'Spark' for building web apps using natural language",
    ],
    pros: [
      "Enhances developer productivity",
      "Seamless integration with popular IDEs",
      "Supports a variety of programming languages",
      "Regular updates and improvements",
    ],
    cons: [
      "Subscription-based pricing",
      "May generate incorrect or insecure code",
      "Limited customization options",
    ],
    openSource: false,
    apiAccess: false,
    documentationQuality: "Excellent",
    communitySize: "Very Large",
    lastUpdated: "April 2025",
    languages: ["Python", "JavaScript", "TypeScript", "Ruby", "Go"],
    reviewCount: 1500,
    reviewUrl: "https://example.com/reviews/github-copilot",
  },
  {
    id: "cursor",
    name: "Cursor",
    description:
      "An AI-powered integrated development environment (IDE) that enhances developer productivity by integrating advanced AI features directly into the coding environment.",
    category: "ide",
    categoryName: "AI IDEs",
    pricing: "Freemium",
    websiteUrl: "https://www.cursor.so",
    githubUrl: undefined,
    logoUrl: "/placeholder.svg?height=40&width=40",
    features: [
      "Forked from Visual Studio Code with additional AI features",
      "Supports models like Claude 3.7 Sonnet, DeepSeek R1, and GPT-4o",
      "Offers a Privacy Mode ensuring user code is never stored remotely",
      "Provides code generation, smart rewrites, and codebase queries",
    ],
    pros: [
      "Enhanced coding experience with AI assistance",
      "Supports multiple AI models",
      "Privacy-focused features",
      "Active development community",
    ],
    cons: [
      "May have a learning curve for new users",
      "Limited offline capabilities",
      "Freemium model may restrict some features",
    ],
    openSource: false,
    apiAccess: false,
    documentationQuality: "Good",
    communitySize: "Large",
    lastUpdated: "April 2025",
    languages: ["Python", "JavaScript", "TypeScript", "Go"],
    reviewCount: 1200,
    reviewUrl: "https://example.com/reviews/cursor",
  },
  {
    id: "qodo",
    name: "Qodo",
    description:
      "An AI-driven code integrity platform that assists in code generation, testing, and review throughout the software development lifecycle.",
    category: "code-integrity",
    categoryName: "Code Integrity Tools",
    pricing: "Freemium",
    websiteUrl: "https://www.qodo.ai",
    githubUrl: undefined,
    logoUrl: "/placeholder.svg?height=40&width=40",
    features: [
      "Provides tools like TestGPT for test generation and AlphaCodium for advanced code generation",
      "Integrates with JetBrains and VSCode IDEs",
      "Supports models like GPT family, Claude Sonnet 3.5, and proprietary models",
    ],
    pros: [
      "Enhances code quality and reliability",
      "Seamless integration with popular IDEs",
      "Supports multiple AI models",
      "Regular updates and feature additions",
    ],
    cons: [
      "Freemium model may limit access to advanced features",
      "May require configuration for optimal results",
      "Limited offline functionality",
    ],
    openSource: false,
    apiAccess: true,
    documentationQuality: "Very Good",
    communitySize: "Medium",
    lastUpdated: "April 2025",
    languages: ["Python", "JavaScript", "TypeScript", "Java"],
    reviewCount: 950,
    reviewUrl: "https://example.com/reviews/qodo",
  },
  {
    id: "amazon-q-developer",
    name: "Amazon Q Developer",
    description:
      "An AI assistant developed by Amazon Web Services (AWS) aimed at enhancing developer productivity by automating routine tasks.",
    category: "ai-assistant",
    categoryName: "AI Assistants",
    pricing: "Pay-per-use",
    websiteUrl: "https://aws.amazon.com/q/",
    githubUrl: undefined,
    logoUrl: "/placeholder.svg?height=40&width=40",
    features: [
      "Assists in code generation, debugging, and documentation",
      "Multilingual capabilities, supporting various programming languages",
      "Integrated within AWS ecosystem, facilitating seamless cloud development",
    ],
    pros: [
      "Boosts developer productivity",
      "Deep integration with AWS services",
      "Supports a wide range of programming languages",
      "Regular updates and enhancements",
    ],
    cons: [
      "Pay-per-use pricing may accumulate costs",
      "Limited functionality outside AWS ecosystem",
      "May require AWS account setup",
    ],
    openSource: false,
    apiAccess: true,
    documentationQuality: "Excellent",
    communitySize: "Large",
    lastUpdated: "April 2025",
    languages: ["Python", "JavaScript", "TypeScript", "Java", "Go"],
    reviewCount: 1100,
    reviewUrl: "https://example.com/reviews/amazon-q-developer",
  },
  {
    id: "canva-code",
    name: "Canva Code",
    description:
      "A feature within Canva's Visual Suite 2.0 that allows users to generate websites and interactive content using AI.",
    category: "design-to-code",
    categoryName: "Design to Code Tools",
    pricing: "Freemium",
    websiteUrl: "https://www.canva.com",
    githubUrl: undefined,
    logoUrl: "/placeholder.svg?height=40&width=40",
    features: [
      "Generates code for websites and interactive content via text prompts",
      "Integrates with Canva's suite of design tools",
      "Includes AI-generated insights and charts within Canva Sheets",
    ],
    pros: [
      "Simplifies the design-to-code process",
      "Seamless integration with design tools",
      "Helps non-developers generate functional code",
    ],
    cons: [
      "Limited to Canva ecosystem",
      "May produce generic code output",
      "Freemium model restricts advanced capabilities",
    ],
    openSource: false,
    apiAccess: false,
    documentationQuality: "Good",
    communitySize: "Large",
    lastUpdated: "April 2025",
    languages: ["JavaScript", "TypeScript"],
    reviewCount: 700,
    reviewUrl: "https://example.com/reviews/canva-code",
  },
  {
    id: "gemini-code-assist",
    name: "Gemini Code Assist",
    description:
      "An AI-powered coding assistant developed by Google, integrated within the Vertex AI platform to provide real-time code suggestions and completions.",
    category: "coding-assistant",
    categoryName: "Coding Assistants",
    pricing: "Pay-per-use",
    websiteUrl: "https://cloud.google.com/vertex-ai",
    githubUrl: undefined,
    logoUrl: "/placeholder.svg?height=40&width=40",
    features: [
      "Real-time code suggestions and completions",
      "Multi-agent communication support",
      "Seamless integration with Google Cloud services",
      "Support for multiple programming languages",
    ],
    pros: [
      "Strong integration within Google Cloud ecosystem",
      "Scalable and reliable",
      "Supports complex code structures",
      "Regular updates",
    ],
    cons: [
      "Pay-per-use pricing can be expensive at scale",
      "Limited community resources compared to established tools",
      "Newer in market",
    ],
    openSource: false,
    apiAccess: true,
    documentationQuality: "Good",
    communitySize: "Medium",
    lastUpdated: "April 2025",
    languages: ["Python", "JavaScript", "TypeScript", "Java"],
    reviewCount: 600,
    reviewUrl: "https://example.com/reviews/gemini-code-assist",
  },
  {
    id: "aider",
    name: "Aider",
    description:
      "An AI coding assistant that integrates with various large language models to provide intelligent code suggestions and completions.",
    category: "coding-assistant",
    categoryName: "Coding Assistants",
    pricing: "Subscription",
    websiteUrl: "https://aider.chat",
    githubUrl: undefined,
    logoUrl: "/placeholder.svg?height=40&width=40",
    features: [
      "Integrates with multiple LLMs including GPT-4o and Claude 3.7 Sonnet",
      "Context-aware code generation",
      "Real-time debugging suggestions",
      "Customizable integration with local and remote models",
    ],
    pros: [
      "Flexibility in LLM integration",
      "Enhanced debugging support",
      "Active development and community",
      "Improves coding efficiency",
    ],
    cons: [
      "Subscription pricing can add up for individuals",
      "May require tuning for optimal performance",
      "Less mature compared to some competitors",
    ],
    openSource: false,
    apiAccess: true,
    documentationQuality: "Very Good",
    communitySize: "Medium",
    lastUpdated: "April 2025",
    languages: ["Python", "JavaScript", "TypeScript"],
    reviewCount: 450,
    reviewUrl: "https://example.com/reviews/aider",
  },
  {
    id: "codeium",
    name: "Codeium",
    description:
      "An AI-powered code completion tool that provides real-time suggestions and accelerates the coding process across popular IDEs.",
    category: "coding-assistant",
    categoryName: "Coding Assistants",
    pricing: "Free / Subscription",
    websiteUrl: "https://codeium.com",
    githubUrl: undefined,
    logoUrl: "/placeholder.svg?height=40&width=40",
    features: [
      "Real-time code completions",
      "Support for multiple languages",
      "IDE integrations including VSCode and JetBrains",
      "Context-aware suggestion engine",
    ],
    pros: [
      "Boosts coding speed",
      "Free version available",
      "Continuous improvements",
      "User-friendly interface",
    ],
    cons: [
      "May require subscription for advanced features",
      "Occasional inaccuracies in suggestions",
      "Limited offline capabilities",
    ],
    openSource: false,
    apiAccess: false,
    documentationQuality: "Good",
    communitySize: "Large",
    lastUpdated: "April 2025",
    languages: ["Python", "JavaScript", "TypeScript", "Ruby"],
    reviewCount: 800,
    reviewUrl: "https://example.com/reviews/codeium",
  },
  {
    id: "tabnine",
    name: "Tabnine",
    description:
      "An AI code completion tool that uses machine learning models trained on open-source code to provide intelligent coding suggestions.",
    category: "coding-assistant",
    categoryName: "Coding Assistants",
    pricing: "Freemium / Subscription",
    websiteUrl: "https://www.tabnine.com",
    githubUrl: undefined,
    logoUrl: "/placeholder.svg?height=40&width=40",
    features: [
      "Real-time code completions",
      "Support for multiple programming languages",
      "Cloud-based and on-premises options",
      "Team collaboration features",
    ],
    pros: [
      "Widely adopted by developers",
      "Flexible deployment options",
      "Enhances code quality",
      "Integrates with popular IDEs",
    ],
    cons: [
      "Freemium model limits advanced features",
      "Suggestions can sometimes be generic",
      "May require fine-tuning for large teams",
    ],
    openSource: false,
    apiAccess: false,
    documentationQuality: "Very Good",
    communitySize: "Very Large",
    lastUpdated: "April 2025",
    languages: ["Python", "JavaScript", "TypeScript", "Java", "Go"],
    reviewCount: 950,
    reviewUrl: "https://example.com/reviews/tabnine",
  },
  {
    id: "askcodi",
    name: "AskCodi",
    description:
      "An AI-powered coding assistant that helps developers with on-demand code generation and debugging insights using large language models.",
    category: "coding-assistant",
    categoryName: "Coding Assistants",
    pricing: "Subscription",
    websiteUrl: "https://askcodi.com",
    githubUrl: undefined,
    logoUrl: "/placeholder.svg?height=40&width=40",
    features: [
      "Instant code generation on request",
      "Debugging assistance and error analysis",
      "Context-aware code completions",
      "Integration with popular development tools",
    ],
    pros: [
      "Speeds up coding and debugging",
      "User-friendly interface",
      "Great for rapid prototyping",
      "Active and responsive support",
    ],
    cons: [
      "Subscription costs can add up",
      "May produce less optimal code in complex scenarios",
      "Limited offline support",
    ],
    openSource: false,
    apiAccess: true,
    documentationQuality: "Good",
    communitySize: "Medium",
    lastUpdated: "April 2025",
    languages: ["Python", "JavaScript", "TypeScript"],
    reviewCount: 500,
    reviewUrl: "https://example.com/reviews/askcodi",
  },
  {
    id: "jules",
    name: "Jules (Google)",
    description:
      "An AI-powered code agent designed by Google to assist developers in identifying and resolving code errors, particularly in Python and JavaScript projects.",
    category: "debugging",
    categoryName: "Debugging Tools",
    pricing: "Free (Limited Beta)",
    websiteUrl: "https://www.google.com/labs/jules",
    githubUrl: undefined,
    logoUrl: "/placeholder.svg?height=40&width=40",
    features: [
      "Automated code error detection",
      "Integration with GitHub workflows",
      "Utilizes Gemini 2.0 for bug fixes",
      "Suggests code corrections",
    ],
    pros: [
      "Improves code stability",
      "Seamless integration with existing workflows",
      "Effective in identifying common errors",
      "User-friendly correction suggestions",
    ],
    cons: [
      "Currently in beta with limited availability",
      "Focused primarily on Python and JavaScript",
      "May not catch all edge-case errors",
    ],
    openSource: false,
    apiAccess: true,
    documentationQuality: "Moderate",
    communitySize: "Small",
    lastUpdated: "April 2025",
    languages: ["Python", "JavaScript"],
    reviewCount: 300,
    reviewUrl: "https://example.com/reviews/jules",
  },
  {
    id: "manus",
    name: "Manus",
    description:
      "An autonomous AI agent capable of executing complex online tasks such as website creation and stock analysis, without continuous human guidance.",
    category: "automation",
    categoryName: "Automation Agents",
    pricing: "Subscription",
    websiteUrl: "https://manus.im",
    githubUrl: undefined,
    logoUrl: "/placeholder.svg?height=40&width=40",
    features: [
      "Automates website creation",
      "Performs stock analysis and schedule management",
      "Operates asynchronously in the cloud",
      "Demonstrates high performance on real-world tasks",
    ],
    pros: [
      "Reduces manual workload",
      "Operates autonomously",
      "Highly versatile in task execution",
      "Strong performance on benchmarks",
    ],
    cons: [
      "Subscription pricing",
      "Requires robust cloud infrastructure",
      "May need human oversight for complex tasks",
    ],
    openSource: false,
    apiAccess: true,
    documentationQuality: "Good",
    communitySize: "Medium",
    lastUpdated: "April 2025",
    languages: ["JavaScript", "Python"],
    reviewCount: 350,
    reviewUrl: "https://example.com/reviews/manus",
  },
  {
    id: "coderabbit",
    name: "CodeRabbit",
    description:
      "An AI code review tool that automates the process of scanning code for potential errors and suggests improvements to enhance code quality.",
    category: "code-review",
    categoryName: "Code Review Tools",
    pricing: "Freemium",
    websiteUrl: "https://coderabbit.ai",
    githubUrl: undefined,
    logoUrl: "/placeholder.svg?height=40&width=40",
    features: [
      "Automated code scanning",
      "Real-time suggestions for improvements",
      "Integrates with existing code review workflows",
      "Identifies common pitfalls and vulnerabilities",
    ],
    pros: [
      "Speeds up code review process",
      "Improves overall code quality",
      "User-friendly interface",
      "Active development",
    ],
    cons: [
      "Freemium model limits advanced features",
      "May flag false positives",
      "Less effective on complex codebases",
    ],
    openSource: false,
    apiAccess: true,
    documentationQuality: "Good",
    communitySize: "Medium",
    lastUpdated: "April 2025",
    languages: ["Python", "JavaScript", "TypeScript"],
    reviewCount: 280,
    reviewUrl: "https://example.com/reviews/coderabbit",
  },
  {
    id: "v0-by-vercel",
    name: "v0 by Vercel",
    description:
      "An AI design tool that translates design prototypes into code, streamlining the design-to-deployment workflow within Vercel's ecosystem.",
    category: "design-to-code",
    categoryName: "Design to Code Tools",
    pricing: "Freemium",
    websiteUrl: "https://vercel.com/v0",
    githubUrl: undefined,
    logoUrl: "/placeholder.svg?height=40&width=40",
    features: [
      "Automated layout suggestions",
      "Quick prototyping from design mockups",
      "Integrates with Vercel's deployment platform",
      "Reduces manual conversion from design to code",
    ],
    pros: [
      "Speeds up the design-to-code process",
      "Seamless integration with deployment workflows",
      "User-friendly design interface",
      "Regular improvements",
    ],
    cons: [
      "Freemium model may limit advanced features",
      "Reliant on Vercel ecosystem",
      "Occasional inconsistencies in code output",
    ],
    openSource: false,
    apiAccess: false,
    documentationQuality: "Good",
    communitySize: "Medium",
    lastUpdated: "April 2025",
    languages: ["JavaScript", "TypeScript"],
    reviewCount: 320,
    reviewUrl: "https://example.com/reviews/v0-by-vercel",
  },
  {
    id: "outerbase",
    name: "Outerbase",
    description:
      "An AI-powered data platform that blends database management with data visualization, enabling teams to derive insights faster.",
    category: "data-platform",
    categoryName: "Data Platforms",
    pricing: "Subscription",
    websiteUrl: "https://outerbase.ai",
    githubUrl: undefined,
    logoUrl: "/placeholder.svg?height=40&width=40",
    features: [
      "Unified interface for database management and visualization",
      "Simplified querying and real-time analytics",
      "Collaboration tools for teams",
      "Integration with popular data sources",
    ],
    pros: [
      "Streamlines data workflows",
      "Powerful visualization capabilities",
      "Facilitates team collaboration",
      "Regular feature updates",
    ],
    cons: [
      "Subscription-based pricing",
      "May require training for advanced features",
      "Limited customization options",
    ],
    openSource: false,
    apiAccess: true,
    documentationQuality: "Very Good",
    communitySize: "Medium",
    lastUpdated: "April 2025",
    languages: ["SQL", "Python", "JavaScript"],
    reviewCount: 400,
    reviewUrl: "https://example.com/reviews/outerbase",
  },
]

async function main() {
  console.log(`Start seeding ...`)

  // Clear existing data
  await prisma.tool.deleteMany();
  console.log("Deleted records in tool table");

  for (const tool of toolsData) {
    // Map the data to match the Prisma schema
    const toolData = {
      name: tool.name,
      description: tool.description,
      logoUrl: tool.logoUrl,
      category: tool.category,
      pricing: tool.pricing,
      websiteUrl: tool.websiteUrl,
      githubUrl: tool.githubUrl === undefined ? null : tool.githubUrl, // Convert undefined to null
      openSource: tool.openSource ?? false, // Provide default if undefined
      apiAccess: tool.apiAccess ?? false, // Provide default if undefined
      documentationQuality: tool.documentationQuality,
      communitySize: tool.communitySize,
      lastUpdated: tool.lastUpdated,
      features: tool.features,
      pros: tool.pros,
      cons: tool.cons,
      languages: tool.languages,
      reviewCount: tool.reviewCount === undefined ? null : tool.reviewCount, // Convert undefined to null
      reviewUrl: tool.reviewUrl === undefined ? null : tool.reviewUrl, // Convert undefined to null
    };

    // Check for nullish values that should be omitted if optional in the schema
    Object.keys(toolData).forEach(key => {
      if (toolData[key as keyof typeof toolData] === undefined || toolData[key as keyof typeof toolData] === null) {
        // Only delete if the field is truly optional in the schema
        // Assuming all fields are optional except those explicitly marked as required
        const requiredFields = ['name', 'description', 'category', 'websiteUrl'];
        if (!requiredFields.includes(key)) {
           delete toolData[key as keyof typeof toolData];
        }
      }
    });

    await prisma.tool.create({
      data: toolData,
    });
    console.log(`Created tool with name: ${tool.name}`)
  }

  console.log(`Seeding finished.`)
}

main()
  .catch((e) => {
    console.error(e)
    process.exit(1)
  })
  .finally(async () => {
    await prisma.$disconnect()
  }) 