import { createMetadata } from '@/utils/createMetadata'
import PublicationsClient from './publications-client'

export const metadata = createMetadata({
  title: "Zachary Proser's publications",
  description: "Searchable list of Zachary Proser's publications",
  author: "Zachary Proser",
  type: "website",
});

// Combine existing publication data with new structure
const publications = [
  {
    id: 50,
    title: "Ruby SAML CVE-2024-45409",
    date: "October 2024",
    publisher: "WorkOS Blog",
    category: "Security",
    tags: ["Ruby", "SAML", "CVE", "Security Vulnerabilities"],
    url: "https://workos.com/blog/ruby-saml-cve-2024-45409",
    abstract: "Analysis of the Ruby SAML vulnerability CVE-2024-45409 and how to mitigate it in your applications.",
    featured: true,
  },
  {
    id: 49,
    title: "How to Secure RAG Applications with Fine-Grained Authorization: Tutorial with Code",
    date: "January 2025",
    publisher: "WorkOS Blog",
    category: "Security",
    tags: ["RAG", "Fine-Grained Authorization", "Security", "Tutorial"],
    url: "https://workos.com/blog/how-to-secure-rag-applications-with-fine-grained-authorization-tutorial-with-code",
    abstract: "A practical guide to implementing fine-grained authorization in Retrieval Augmented Generation applications.",
    featured: false,
  },
  {
    id: 48,
    title: "Top 5 Google Zanzibar Open Source Implementations in 2024",
    date: "January 2025",
    publisher: "WorkOS Blog",
    category: "Authorization",
    tags: ["Google Zanzibar", "Open Source", "Authorization"],
    url: "https://workos.com/blog/top-5-google-zanzibar-open-source-implementations-in-2024",
    abstract: "A comparison of the top open source implementations of Google's Zanzibar authorization system.",
    featured: true,
  },
  {
    id: 47,
    title: "Best Practices for CLI Authentication: A Technical Guide",
    date: "December 2024",
    publisher: "WorkOS Blog",
    category: "Authentication",
    tags: ["CLI", "Authentication", "Security"],
    url: "https://workos.com/blog/best-practices-for-cli-authentication-a-technical-guide",
    abstract: "Technical best practices for implementing secure authentication in command-line interfaces.",
    featured: false,
  },
  {
    id: 46,
    title: "How to Build Browser-Based OAuth into Your CLI with WorkOS",
    date: "February 2025",
    publisher: "WorkOS Blog",
    category: "Authentication",
    tags: ["OAuth", "CLI", "Browser Authentication"],
    url: "https://workos.com/blog/how-to-build-browser-based-oauth-into-your-cli-with-workos",
    abstract: "A step-by-step guide to implementing browser-based OAuth authentication in command-line tools.",
    featured: true,
  },
  {
    id: 45,
    title: "Actions",
    date: "February 2025",
    publisher: "WorkOS Blog",
    category: "Development",
    tags: ["Actions", "Automation", "Workflows"],
    url: "https://workos.com/blog/actions",
    abstract: "An introduction to WorkOS Actions for automating workflows and responses to security events.",
    featured: false,
  },
  {
    id: 44,
    title: "How to Build Document Access Control with S3, WorkOS FGA, and Lambda Authorizers",
    date: "February 2025",
    publisher: "WorkOS Blog",
    category: "Authorization",
    tags: ["S3", "Fine-Grained Authorization", "Lambda"],
    url: "https://workos.com/blog/how-to-build-document-access-control-with-s3-workos-fga-and-lambda-authorizers",
    abstract: "A comprehensive guide to implementing document-level access control using AWS S3, WorkOS FGA, and Lambda authorizers.",
    featured: true,
  },
  {
    id: 43,
    title: "What is Multitenant Authentication?",
    date: "February 2025",
    publisher: "WorkOS Blog",
    category: "Authentication",
    tags: ["Multitenancy", "Authentication", "SaaS"],
    url: "https://workos.com/blog/what-is-multitenant-authentication",
    abstract: "Understanding multitenant authentication and its implementation in modern SaaS applications.",
    featured: false,
  },
  {
    id: 42,
    title: "AuthQuake: Microsoft's MFA System Vulnerable to TOTP Brute Force Attack",
    date: "February 2025",
    publisher: "WorkOS Blog",
    category: "Security",
    tags: ["MFA", "TOTP", "Security Vulnerabilities", "Microsoft"],
    url: "https://workos.com/blog/authquake-microsofts-mfa-system-vulnerable-to-totp-brute-force-attack",
    abstract: "Analysis of the vulnerability in Microsoft's MFA system that allows brute force attacks against TOTP codes.",
    featured: true,
  },
  {
    id: 41,
    title: "WASM Auth Server: Golang to JS",
    date: "February 2025",
    publisher: "WorkOS Blog",
    category: "Development",
    tags: ["WASM", "Golang", "Authentication", "JavaScript"],
    url: "https://workos.com/blog/wasm-auth-server-golang-to-js",
    abstract: "Building an authentication server with WebAssembly by compiling Golang to JavaScript.",
    featured: false,
  },
  {
    id: 40,
    title: "How to Build Row-Level Access Control with WorkOS FGA and Postgres",
    date: "February 2025",
    publisher: "WorkOS Blog",
    category: "Authorization",
    tags: ["Postgres", "Fine-Grained Authorization", "Row-Level Security"],
    url: "https://workos.com/blog/how-to-build-row-level-access-control-with-workos-fga-and-postgres",
    abstract: "A practical guide to implementing row-level access control in PostgreSQL using WorkOS Fine-Grained Authorization.",
    featured: true,
  },
  {
    id: 39,
    title: "Best Practices for Secrets Management",
    date: "February 2025",
    publisher: "WorkOS Blog",
    category: "Security",
    tags: ["Secrets Management", "Security", "DevOps"],
    url: "https://workos.com/blog/best-practices-for-secrets-management",
    abstract: "Essential best practices for securely managing secrets in modern applications and infrastructure.",
    featured: false,
  },
  {
    id: 38,
    title: "What is Device Fingerprinting and How Does it Work?",
    date: "January 2025",
    publisher: "WorkOS Blog",
    category: "Security",
    tags: ["Device Fingerprinting", "Security", "Fraud Prevention"],
    url: "https://workos.com/blog/what-is-device-fingerprinting-and-how-does-it-work",
    abstract: "An in-depth explanation of device fingerprinting technology and its applications in security and fraud prevention.",
    featured: true,
  },
  {
    id: 37,
    title: "How WorkOS Radar Really Works",
    date: "January 2025",
    publisher: "WorkOS Blog",
    category: "Security",
    tags: ["Radar", "Authentication Security", "Fraud Prevention"],
    url: "https://workos.com/blog/how-workos-radar-really-works",
    abstract: "A behind-the-scenes look at how WorkOS Radar protects applications from authentication attacks and fraud.",
    featured: false,
  },
  {
    id: 36,
    title: "How WorkOS Radar's Bot Detection Works",
    date: "January 2025",
    publisher: "WorkOS Blog",
    category: "Security",
    tags: ["Bot Detection", "Security", "Authentication"],
    url: "https://workos.com/blog/how-workos-radars-bot-detection-works",
    abstract: "An exploration of the technology behind WorkOS Radar's bot detection system and how it protects applications.",
    featured: true,
  },
  {
    id: 27,
    title: "How WorkOS Radar Does Rate Limiting with Device Fingerprinting",
    date: "February 2025",
    publisher: "WorkOS Blog",
    category: "Security",
    tags: ["Rate Limiting", "Device Fingerprinting", "Security"],
    url: "https://workos.com/blog/how-workos-radar-does-rate-limiting-with-device-fingerprinting",
    abstract: "An exploration of how device fingerprinting can be used to implement effective rate limiting for web applications.",
    featured: true,
  },
  {
    id: 28,
    title: "DeepSeek R1 Pushes Local and Open AI Forward",
    date: "February 2025",
    publisher: "WorkOS Blog",
    category: "AI",
    tags: ["DeepSeek", "Open Source", "Local AI"],
    url: "https://workos.com/blog/deepseek-r1-pushes-local-and-open-ai-forward",
    abstract: "How DeepSeek R1 is advancing the capabilities of local and open-source AI models.",
    featured: false,
  },
  {
    id: 29,
    title: "Shadcn UI: What is it, and why do you care?",
    date: "February 2025",
    publisher: "WorkOS Blog",
    category: "UI Development",
    tags: ["Shadcn UI", "React", "Component Libraries"],
    url: "https://workos.com/blog/shadcn-ui",
    abstract: "A comprehensive guide to using Shadcn UI for building modern React applications.",
    featured: true,
  },
  {
    id: 30,
    title: "What is Ente Auth?",
    date: "February 2025",
    publisher: "WorkOS Blog",
    category: "Authentication",
    tags: ["Ente Auth", "Authentication", "Security"],
    url: "https://workos.com/blog/what-is-ente-auth",
    abstract: "An introduction to Ente Auth and its approach to secure, privacy-focused authentication.",
    featured: false,
  },
  {
    id: 31,
    title: "What is Authentik?",
    date: "February 2025",
    publisher: "WorkOS Blog",
    category: "Authentication",
    tags: ["Authentik", "Identity Management", "Open Source"],
    url: "https://workos.com/blog/what-is-authentik",
    abstract: "Exploring Authentik, an open-source identity management solution for modern applications.",
    featured: true,
  },
  {
    id: 32,
    title: "How to Run DeepSeek R1 Locally",
    date: "February 2025",
    publisher: "WorkOS Blog",
    category: "AI",
    tags: ["DeepSeek", "Local AI", "Tutorials"],
    url: "https://workos.com/blog/how-to-run-deepseek-r1-locally",
    abstract: "A step-by-step guide to running DeepSeek R1 on your local machine for AI development.",
    featured: false,
  },
  {
    id: 33,
    title: "What Does It Mean to Distill a Machine Learning Model or LLM?",
    date: "February 2025",
    publisher: "WorkOS Blog",
    category: "AI",
    tags: ["Model Distillation", "LLMs", "Machine Learning"],
    url: "https://workos.com/blog/what-does-it-mean-to-distill-a-machine-learning-model-or-llm",
    abstract: "Understanding the process of model distillation and its importance in creating efficient AI models.",
    featured: true,
  },
  {
    id: 34,
    title: "How to Build Secure AI Agents that are Enterprise Ready",
    date: "February 2025",
    publisher: "WorkOS Blog",
    category: "Security",
    tags: ["AI Agents", "Enterprise Security", "Compliance"],
    url: "https://workos.com/blog/ai-agents-security-building-trust-in-enterprise-intelligence",
    abstract: "Best practices for building secure, compliant AI agents for enterprise environments.",
    featured: false,
  },
  {
    id: 35,
    title: "What is Arcade.dev? An LLM Tool Calling Platform",
    date: "February 2025",
    publisher: "WorkOS Blog",
    category: "AI",
    tags: ["Arcade.dev", "LLM", "Tool Calling"],
    url: "https://workos.com/blog/what-is-arcade-dev-an-llm-tool-calling-platform",
    abstract: "An introduction to Arcade.dev, a platform that simplifies authentication and tool management for LLM applications.",
    featured: true,
  },
  {
    id: 18,
    title: "What is the difference between Radix and Shadcn UI?",
    date: "February 2025",
    publisher: "WorkOS Blog",
    category: "UI Development",
    tags: ["Radix UI", "Shadcn UI", "Component Libraries", "React"],
    url: "https://workos.com/blog/what-is-the-difference-between-radix-and-shadcn-ui",
    abstract: "A comparison of Radix UI's unstyled primitives and Shadcn UI's styled components approach for modern React applications.",
    featured: true,
  },
  {
    id: 19,
    title: "AI Agents Are Taking Over",
    date: "February 2025",
    publisher: "WorkOS Blog",
    category: "AI",
    tags: ["AI Agents", "Automation", "Future of Work"],
    url: "https://workos.com/blog/ai-agents-are-taking-over",
    abstract: "Exploring how AI agents are transforming workflows and automating complex tasks across industries.",
    featured: false,
  },
  {
    id: 20,
    title: "The Best Feature Flag Providers for Apps in 2025",
    date: "February 2025",
    publisher: "WorkOS Blog",
    category: "DevOps",
    tags: ["Feature Flags", "Development", "DevOps"],
    url: "https://workos.com/blog/the-best-feature-flag-providers-for-apps-in-2025",
    abstract: "A comprehensive review of the top feature flag providers and how they can improve your development workflow.",
    featured: true,
  },
  {
    id: 21,
    title: "Securing AI Agents: Operator Models and Authentication",
    date: "February 2025",
    publisher: "WorkOS Blog",
    category: "Security",
    tags: ["AI Security", "Authentication", "Operator Models"],
    url: "https://workos.com/blog/securing-ai-agents-operator-models-and-authentication",
    abstract: "Best practices for implementing secure authentication and authorization for AI agent systems.",
    featured: false,
  },
  {
    id: 22,
    title: "Context is King: Tools for Feeding Your Code and Website to LLMs",
    date: "February 2025",
    publisher: "WorkOS Blog",
    category: "AI",
    tags: ["LLMs", "Context Window", "AI Tools"],
    url: "https://workos.com/blog/context-is-king-tools-for-feeding-your-code-and-website-to-llms",
    abstract: "An overview of tools and techniques for effectively providing context to large language models.",
    featured: true,
  },
  {
    id: 23,
    title: "What is API Authentication? A Guide to OAuth 2.0, JWT, and Key Methods",
    date: "February 2025",
    publisher: "WorkOS Blog",
    category: "Security",
    tags: ["API Authentication", "OAuth 2.0", "JWT"],
    url: "https://workos.com/blog/what-is-api-authentication-a-guide-to-oauth-2-0-jwt-and-key-methods",
    abstract: "A comprehensive guide to modern API authentication methods and best practices.",
    featured: false,
  },
  {
    id: 24,
    title: "OAuth 2.0 and OpenID Connect: The Evolution from Authorization to Identity",
    date: "February 2025",
    publisher: "WorkOS Blog",
    category: "Security",
    tags: ["OAuth 2.0", "OpenID Connect", "Authentication"],
    url: "https://workos.com/blog/oauth-2-0-and-openid-connect-the-evolution-from-authorization-to-identity",
    abstract: "How OpenID Connect builds on OAuth 2.0 to provide standardized identity and authentication.",
    featured: true,
  },
  {
    id: 25,
    title: "How to Add Custom Claims to JWTs",
    date: "February 2025",
    publisher: "WorkOS Blog",
    category: "Development",
    tags: ["JWT", "Authentication", "Custom Claims"],
    url: "https://workos.com/blog/how-to-add-custom-claims-to-jwts",
    abstract: "A practical guide to enriching JSON Web Tokens with custom claims for enhanced application logic.",
    featured: false,
  },
  {
    id: 26,
    title: "What is the aud Claim in Identity, Authentication, and Authorization?",
    date: "February 2025",
    publisher: "WorkOS Blog",
    category: "Security",
    tags: ["JWT", "Authentication", "aud Claim"],
    url: "https://workos.com/blog/what-is-the-aud-claim-in-identity",
    abstract: "Understanding the audience claim in JWTs and its role in secure authentication systems.",
    featured: true,
  },
  {
    id: 51,
    title: "Building Privacy-Aware Software with Vector Databases",
    date: "June 2024",
    publisher: "Pinecone Learning Center",
    category: "Security",
    tags: ["Privacy", "Vector Databases", "Data Protection"],
    url: "https://www.pinecone.io/learn/privacy-aware-software/",
    abstract: "Best practices for implementing privacy-preserving techniques in applications using vector databases.",
    featured: true,
  },
  {
    id: 1,
    title: "Accelerating Legal Discovery and Analysis with Pinecone and Voyage AI",
    date: "August 2024",
    publisher: "Pinecone Learning Center",
    category: "AI",
    tags: ["Legal Tech", "Vector Search", "AI"],
    url: "https://www.pinecone.io/learn/legal-semantic-search/",
    abstract: "An exploration of how vector databases and AI can transform legal discovery processes.",
    featured: true,
  },
  {
    id: 2,
    title: "When that Adhoc Script Turns Into a Production Pipeline",
    date: "July 2024",
    publisher: "Prefect.io Blog",
    category: "Engineering",
    tags: ["Data Engineering", "Pipelines", "Best Practices"],
    url: "https://www.prefect.io/blog/when-that-adhoc-script-turns-into-a-production-data-pipeline",
    abstract: "Strategies for transforming quick scripts into robust production systems.",
    featured: false,
  },
  {
    id: 3,
    title: "Building Privacy-Aware AI Software with Vector Databases",
    date: "June 2024",
    publisher: "The New Stack",
    category: "AI",
    tags: ["Privacy", "Vector Databases", "AI"],
    url: "https://thenewstack.io/building-privacy-aware-ai-software-with-vector-databases/",
    abstract: "How to implement privacy-preserving techniques in AI applications using vector databases.",
    featured: true,
  },
  {
    id: 4,
    title: "RAG Evaluation: Don't let customers tell you first",
    date: "May 2024",
    publisher: "Pinecone Learning Center",
    category: "AI",
    tags: ["RAG", "Evaluation", "Vector Search"],
    url: "https://www.pinecone.io/learn/series/vector-databases-in-production-for-busy-engineers/rag-evaluation/",
    abstract: "Best practices for evaluating Retrieval Augmented Generation systems before deployment.",
    featured: false,
  },
  {
    id: 5,
    title: "Integrating Cloud-based Vector Databases with CI/CD Pipelines",
    date: "May 2024",
    publisher: "Pinecone Learning Center",
    category: "DevOps",
    tags: ["CI/CD", "Vector Databases", "Cloud"],
    url: "https://www.pinecone.io/learn/series/vector-databases-in-production-for-busy-engineers/ci-cd",
    abstract: "A guide to integrating vector databases into continuous integration and deployment workflows.",
    featured: true,
  },
  {
    id: 6,
    title: "Test Pinecone Serverless at Scale with the AWS Reference Architecture",
    date: "January 2024",
    publisher: "Pinecone Learning Center",
    category: "Cloud",
    tags: ["AWS", "Serverless", "Vector Databases"],
    url: "https://www.pinecone.io/learn/scaling-pinecone-serverless/",
    abstract: "How to test and scale vector database deployments using AWS infrastructure.",
    featured: false,
  },
  {
    id: 7,
    title: "Launch Production-grade architectures using Pinecone's vector database",
    date: "November 2023",
    publisher: "Pinecone Engineering Blog",
    category: "Cloud",
    tags: ["AWS", "Architecture", "Vector Databases"],
    url: "https://www.pinecone.io/blog/aws-reference-architecture/",
    abstract: "A comprehensive guide to deploying production-ready vector database architectures on AWS.",
    featured: true,
  },
  {
    id: 8,
    title: "Exploring the Pinecone AWS Reference Architecture",
    date: "November 2023",
    publisher: "Pinecone Learning Center",
    category: "Cloud",
    tags: ["AWS", "Architecture", "Vector Databases"],
    url: "https://www.pinecone.io/learn/aws-reference-architecture/",
    abstract: "A deep dive into the AWS reference architecture for Pinecone vector databases.",
    featured: false,
  },
  {
    id: 9,
    title: "Making it easier to maintain open-source projects with CodiumAI and Pinecone",
    date: "September 2023",
    publisher: "Pinecone Learning Center",
    category: "Open Source",
    tags: ["CodiumAI", "Open Source", "Maintenance"],
    url: "https://www.pinecone.io/learn/codiumai-pinecone-similar-issues/",
    abstract: "How to use AI tools to simplify open-source project maintenance and issue tracking.",
    featured: true,
  },
  {
    id: 10,
    title: "The Pain and Poetry of Python",
    date: "August 2023",
    publisher: "Pinecone Engineering Blog",
    category: "Programming",
    tags: ["Python", "Software Development", "Best Practices"],
    url: "https://www.pinecone.io/blog/pain-poetry-python",
    abstract: "An exploration of Python's strengths and weaknesses in modern software development.",
    featured: false,
  },
  {
    id: 11,
    title: "How to use Jupyter Notebooks for Machine Learning and AI",
    date: "August 2023",
    publisher: "Pinecone Learning Center",
    category: "Data Science",
    tags: ["Jupyter", "Machine Learning", "Tutorials"],
    url: "https://www.pinecone.io/learn/jupyter-notebooks/",
    abstract: "A practical guide to leveraging Jupyter Notebooks for machine learning and AI development.",
    featured: true,
  },
  {
    id: 12,
    title: "Retrieval Augmented Generation (RAG)",
    date: "August 2023",
    publisher: "Pinecone Learning Center",
    category: "AI",
    tags: ["RAG", "LLMs", "Vector Search"],
    url: "https://www.pinecone.io/learn/retrieval-augmented-generation",
    abstract: "An introduction to Retrieval Augmented Generation and its applications in AI systems.",
    featured: false,
  },
  {
    id: 13,
    title: "AI-powered and built with...JavaScript?",
    date: "August 2023",
    publisher: "Pinecone Learning Center",
    category: "Programming",
    tags: ["JavaScript", "AI", "Web Development"],
    url: "https://www.pinecone.io/learn/javascript-ai/",
    abstract: "How JavaScript is becoming a viable language for AI application development.",
    featured: true,
  },
  {
    id: 14,
    title: "How to securely store secrets in BitWarden CLI",
    date: "October 2022",
    publisher: "Gruntwork Engineering Blog",
    category: "Security",
    tags: ["BitWarden", "CLI", "Security"],
    url: "https://blog.gruntwork.io/how-to-securely-store-secrets-in-bitwarden-cli-and-load-them-into-your-zsh-shell-when-needed-f12d4d040df",
    abstract: "A guide to securely managing secrets using BitWarden CLI and ZSH shell integration.",
    featured: false,
  },
  {
    id: 15,
    title: "How to write code on Mac or Linux but test on Windows with hot-reloading",
    date: "July 2022",
    publisher: "Gruntwork Engineering Blog",
    category: "DevOps",
    tags: ["Cross-platform", "Development", "Hot-reloading"],
    url: "https://blog.gruntwork.io/how-to-write-code-on-mac-or-linux-but-test-on-windows-with-hot-reloading-b218de5383d1",
    abstract: "Techniques for cross-platform development with efficient testing workflows.",
    featured: false,
  },
  {
    id: 16,
    title: "Introducing cf-terraforming",
    date: "February 2019",
    publisher: "Cloudflare Blog",
    category: "DevOps",
    tags: ["Terraform", "Cloudflare", "Infrastructure as Code"],
    url: "https://blog.cloudflare.com/introducing-cf-terraform",
    abstract: "Introducing a tool to convert Cloudflare configurations to Terraform code.",
    featured: true,
  },
  {
    id: 17,
    title: "Dogfooding Cloudflare Workers",
    date: "May 2018",
    publisher: "Cloudflare Blog",
    category: "Edge Computing",
    tags: ["Cloudflare Workers", "Serverless", "Edge Computing"],
    url: "https://blog.cloudflare.com/dogfooding-edge-workers/",
    abstract: "How Cloudflare uses its own Workers platform to build and improve its services.",
    featured: false,
  },
]

// Extract unique categories and years for filters
const categories = [...new Set(publications.map((pub) => pub.category))].sort()
const years = [...new Set(publications.map((pub) => {
  const dateParts = pub.date.split(" ");
  return dateParts[dateParts.length - 1]; // Get the year part
}))].sort((a, b) => Number.parseInt(b) - Number.parseInt(a))
const allTags = [...new Set(publications.flatMap((pub) => pub.tags))].sort()

export default function PublicationsPage() {
  return (
    <PublicationsClient 
      publications={publications}
      categories={categories}
      years={years}
      allTags={allTags}
    />
  )
}

